import type {
  MemoriesApi,
  MemoryEntry,
  MemoryEntryInput,
} from "../../shared/memories";

const today = new Date().toISOString().slice(0, 10);
let demoEntries: MemoryEntry[] = [
  {
    id: "demo-book",
    mediaType: "book",
    title: "百年孤独",
    creator: "加西亚·马尔克斯",
    releaseYear: 1967,
    seasonLabel: "",
    completedOn: today,
    rating: 5,
    shortReview: "时间在家族里不是一条线，而是一场不断回返的雨。",
    review: "读完后最难忘的不是某一个人物，而是所有人都在重复靠近和错过彼此。",
    tags: ["文学", "重读"],
    isRepeat: true,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-movie",
    mediaType: "movie",
    title: "完美的日子",
    creator: "维姆·文德斯",
    releaseYear: 2023,
    seasonLabel: "",
    completedOn: "2026-08-18",
    rating: 4.5,
    shortReview: "重复的生活并不贫瘠，注意力让每一天长出不同纹理。",
    review: "",
    tags: ["电影", "生活"],
    isRepeat: false,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-series",
    mediaType: "series",
    title: "漫长的季节",
    creator: "辛爽",
    releaseYear: 2023,
    seasonLabel: "全剧",
    completedOn: "2026-08-05",
    rating: 4.5,
    shortReview: "往前看，别回头。可真正打动人的，恰恰是那些不得不回头的时刻。",
    review: "",
    tags: ["剧集", "悬疑"],
    isRepeat: false,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-book-2",
    mediaType: "book",
    title: "悉达多",
    creator: "赫尔曼·黑塞",
    releaseYear: 1922,
    seasonLabel: "",
    completedOn: "2026-08-06",
    rating: 4.7,
    shortReview: "答案并不在远方，而在真正经历过的每一步里。",
    review: "",
    tags: ["成长", "年度推荐"],
    isRepeat: true,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-movie-2",
    mediaType: "movie",
    title: "坠落的审判",
    creator: "茹斯汀·特里耶",
    releaseYear: 2023,
    seasonLabel: "",
    completedOn: "2026-07-29",
    rating: 4.5,
    shortReview: "真相在亲密关系里从来不是唯一视角。",
    review: "",
    tags: ["灵感", "关系"],
    isRepeat: false,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-movie-3",
    mediaType: "movie",
    title: "宇宙探索编辑部",
    creator: "孔大山",
    releaseYear: 2021,
    seasonLabel: "",
    completedOn: "2026-07-18",
    rating: 4.6,
    shortReview: "荒诞抵达尽头时，仍然保留着理解他人的愿望。",
    review: "",
    tags: ["灵感", "理想主义"],
    isRepeat: false,
    coverDataUrl: null,
    coverAttribution: "",
    externalProvider: null,
    externalId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

function mockSave(input: MemoryEntryInput): MemoryEntry {
  const old = input.id ? demoEntries.find((item) => item.id === input.id) : undefined;
  const now = new Date().toISOString();
  const next: MemoryEntry = {
    id: input.id ?? `demo-${Date.now()}`,
    mediaType: input.mediaType,
    title: input.title.trim(),
    creator: input.creator?.trim() ?? "",
    releaseYear: input.releaseYear ?? null,
    seasonLabel: input.seasonLabel?.trim() ?? "",
    completedOn: input.completedOn,
    rating: input.rating ?? null,
    shortReview: input.shortReview?.trim() ?? "",
    review: input.review?.trim() ?? "",
    tags: input.tags ?? [],
    isRepeat: Boolean(input.isRepeat),
    coverDataUrl: input.removeCover ? null : input.coverDataUrl ?? old?.coverDataUrl ?? null,
    coverAttribution: input.coverAttribution ?? old?.coverAttribution ?? "",
    externalProvider: old?.externalProvider ?? null,
    externalId: old?.externalId ?? null,
    createdAt: old?.createdAt ?? now,
    updatedAt: now,
  };
  demoEntries = [next, ...demoEntries.filter((item) => item.id !== next.id)];
  return next;
}

const mockApi: MemoriesApi = {
  async list() { return [...demoEntries].sort((a, b) => b.completedOn.localeCompare(a.completedOn)); },
  async save(input) { return mockSave(input); },
  async remove(id) { demoEntries = demoEntries.filter((item) => item.id !== id); },
  async pickCover() { return null; },
};

export const memoriesApi: MemoriesApi = window.memories ?? mockApi;
